apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw2v1
spec:
  selector:
    matchLabels:
      run: hw2v1
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  template:
    metadata:
      labels:
        run: hw2v1
    spec:
      containers:
      - name: hw2v1
        image: lavibenshimol/kuber:hw2version2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
