apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw2v1
spec:
  selector:
    matchLabels:
      run: hw2v1
  replicas: 1
  template:
    metadata:
      labels:
        run: hw2v1
    spec:
      containers:
      - name: hw2v1
        image: lavibenshimol/kuber:hw2version1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 8m
          requests:
            cpu: 6m

---

apiVersion: v1
kind: Service
metadata:
  name: hw2v1
  labels:
    run: hw2v1
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30555
  selector:
    run: hw2v1

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hw2v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hw2v1
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50